// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBnSxtRctaVKS-lcAiAGALXVXbM6ExBsyY",
    appId: "1:828113347992:android:341aa903260ef97fe3b7ed",
    messagingSenderId: "828113347992",
    projectId: "community-pointsystem",
    storageBucket: "community-pointsystem.firebasestorage.app",
    // apiKey: 'AIzaSyB0WhepzFKflY39YTFqK5HPnuQdRoCtPUU',
    // appId: '1:630468613180:web:67ed70a2c583bd708f1f39',
    // messagingSenderId: '630468613180',
    // projectId: 'doctorapp-61cb4',
    // authDomain: 'doctorapp-61cb4.firebaseapp.com',
    // storageBucket: 'doctorapp-61cb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBnSxtRctaVKS-lcAiAGALXVXbM6ExBsyY",
    appId: "1:828113347992:android:341aa903260ef97fe3b7ed",
    messagingSenderId: "828113347992",
    projectId: "community-pointsystem",
    storageBucket: "community-pointsystem.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBnSxtRctaVKS-lcAiAGALXVXbM6ExBsyY",
    appId: "1:828113347992:android:341aa903260ef97fe3b7ed",
    messagingSenderId: "828113347992",
    projectId: "community-pointsystem",
    storageBucket: "community-pointsystem.firebasestorage.app",
    // apiKey: 'AIzaSyBzRZ0hQLY-5A_JLDZhOoIRu4G4q9W9Z0Q',
    // appId: '1:630468613180:ios:8bcca646a7a85a668f1f39',
    // messagingSenderId: '630468613180',
    // projectId: 'doctorapp-61cb4',
    // storageBucket: 'doctorapp-61cb4.appspot.com',
    // iosBundleId: 'com.example.nfcappNew',
  );
}
